web:
    container_name: web
    image: tutum/nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ./default:/etc/nginx/sites-available/default
        - ./default:/etc/nginx/sites-enabled/default
        - ./site:/usr/share/nginx/html
        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log

phpfpm:
    container_name: php
    image: php:fpm
    ports:
        - "9000:9000"
    volumes:
        - ./site:/usr/share/nginx/html
    links:
        - db

db:
    container_name: db
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DB: cpa-iesi

phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8183:80
    environment:
      MYSQL_USERNAME: admin
      MYSQL_ROOT_PASSWORD: admin
      PMA_ARBITRARY: 1
