web:
  container_name: web
  build: .
  ports:
  - "80:80"
  - "443:443"
  volumes:
  - ./site:/var/www/web/public
  - ./nginx/vhost:/etc/nginx/sites-available/default
  - ./nginx/vhost:/etc/nginx/sites-enabled/default
  - ./nginx/logs/nginx-access.log:/var/log/nginx/access.log
  - ./nginx/logs/nginx-error.log:/var/log/nginx/error.log
  links:
  - db
  tty: true
  command: service php5-fpm restart && service nginx restart

db:
  container_name: db
  image: mysql:5.7
  volumes:
  - ./db:/var/lib/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=xeon2accept
  - MYSQL_DATABASE=cpa-iesi
  - MYSQL_USER=cpd

phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
  - db
  ports:
  - 8183:80
  environment:
    MYSQL_USERNAME: cpd
    MYSQL_ROOT_PASSWORD: xeon2accept
    MA_ARBITRARY: 1
