php:
    image: php:5.6-apache
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./site:/var/www/html
    links:
        - db
    command:
        /bin/bash -c "apt-get update && apt-get install -y g++ && \
        ln -s /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled && \
        ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled && \
        docker-php-ext-install mbstring && \
        apt-get install -y libfreetype6-dev && \
        apt-get install -y libgd-dev && \
        docker-php-ext-configure gd --with-freetype-dir=/usr && \
        docker-php-ext-install gd exif && \
        docker-php-ext-install mysql mysqli pdo pdo_mysql && \
        a2enmod rewrite && \
        apt-get autoremove -y && apt-get clean all"

db:
  image: mysql:5.7
  volumes:
   - ./db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=xeon2accept
   - MYSQL_DATABASE=cpa-iesi
   - MYSQL_USER=cpd
